os:
- linux
language:
- cpp
compiler:
- clang
- gcc
before_install:
- sudo apt-get update -qq
install:
- sudo apt-get install -qq devscripts build-essential equivs python-software-properties
script:
- mkdir build
- cd build
- cmake -DBUILD_EXAMPLES=ON ..
- make
- make test
