os:
- linux
language:
- cpp
compiler:
- clang
- gcc
sudo: false
addons:
    apt:
        packages:
        - devscripts
        - build-essential
        - equivs
        - python-software-properties
script:
- mkdir build
- cd build
- cmake -DBUILD_EXAMPLES=ON ..
- make
- make test
